# Site settings
title: CS 3212 — Algorithms
tagline: Fall 2026 · George Washington University
description: Course website for CS 3212, Algorithms, Fall 2026
author: Aya Zirikly
baseurl: '/algorithms-gw26'
url: 'https://azirikly.github.io'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.12.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
